<<<<<<< HEAD
title: Zhao Yan's Homepage
page-top-title: Zhao Yan
top-section-bg-text: Mechanical Engineering
home-subtitle: Zhao Yan&ensp;|&ensp;赵严
copyright-text: '&copy; Zhao Yan 2025. All Rights Reserved.'
=======
title: Sen Li's Homepage
page-top-title: Sen Li
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
>>>>>>> c612e10e2e068b8b0277aa0a3f989caaa011d2aa
